### ISSUE TITLE
VCCIO Labeling

### ISSUE THREAD

**Issue by meawoppl** [tinyvision-ai-inc/UPduino-v2.1#3]
In the schematic the jumper for `VCCIO_3` is wired in the port on the chip labeled `VCCIO_0`. I don't know if this is a mistake or a strange convention, but it cost me several hours today :/

**Comment by vr2045** [comment]
Yes, strange but true! I can see why this is confusing... This is the
original upduino 2.0 design, I have not made any schematic changes.

There's a new design: please see the upduino 3.0 github. Hope these and
other bugs are fixed there. Board build is in process.

https://github.com/tinyvision-ai-inc/UPduino-v3.0
