### ISSUE TITLE
Can't follow tutorial

### ISSUE THREAD

**Issue by kthakore** [tinyvision-ai-inc/UPduino-v2.1#4]
Hi Venkat,

I am following the 2.1 upduino tutorial here. https://github.com/tinyvision-ai-inc/UPduino-v2.1/blob/master/PROGRAMMING.md

I am stuck with the step `Detect Cable` I have opened lattice diamond programmer but can't find that option or dialog anywhere. It would be great if for novices we could see screenshots of the steps.

**Comment by kthakore** [comment]
Can't open the Programmer tool (under tools > Programmer) as it is grayed out before opening a project. However when I open a project I don't know what settings to put and just use the default. Once I do get the programmer open and do the detect cable it conflicts with the project settings selected.

**Comment by kthakore** [comment]
![image](https://user-images.githubusercontent.com/21407/73993453-11c5dd00-4907-11ea-8ed4-d6d6dc73f16c.png)

Can't open the programmer

**Comment by vr2045** [comment]
I use the icon for the radiant programmer, never done this from the main
gui.

Also, suggest trying out iceprog which works every time and is fast.

**Comment by kthakore** [comment]
Thanks!
